include .env

export RDS_ADMIN_PASSWORD
export RDS_ADMIN_USER
export RDS_ADMIN_HOST
export RDS_ADMIN_PORT
export RDS_ADMIN_DATABASE

.PHONY: reset-databases
reset-databases:
	@PGPASSWORD=$(RDS_ADMIN_PASSWORD) psql -h $(RDS_ADMIN_HOST) -U $(RDS_ADMIN_USER) -p $(RDS_ADMIN_PORT) -d $(RDS_ADMIN_DATABASE) \
		-c "DROP DATABASE IF EXISTS dev;"
	@PGPASSWORD=$(RDS_ADMIN_PASSWORD) psql -h $(RDS_ADMIN_HOST) -U $(RDS_ADMIN_USER) -p $(RDS_ADMIN_PORT) -d $(RDS_ADMIN_DATABASE) \
		-c "DROP DATABASE IF EXISTS prod;"

